steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/friendly-lamp-440702-i5/solanki-flask-app:sha256:9e9899b79c8a80c48112d56fb7f22318a598ae5b0347a300e2cf97ffc6dc96a6', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/friendly-lamp-440702-i5/solanki-flask-app:sha256:9e9899b79c8a80c48112d56fb7f22318a598ae5b0347a300e2cf97ffc6dc96a6']

  # Step 3: SSH into the Compute Engine and update the container
  -  name: 'gcr.io/cloud-builders/gcloud'
     args:
      - 'compute'
      - 'instances'
      - 'set-container-configuration'
      - '--zone=us-east1-a'
      - '--instance=solanki-flask-instance'
      - '--container-image=gcr.io/friendly-lamp-440702-i5/solanki-flask-app:sha256:9e9899b79c8a80c48112d56fb7f22318a598ae5b0347a300e2cf97ffc6dc96a6'
options:

logs_bucket: 'gs://log_bucket-solanki'  # Specify the Cloud Storage bucket for logs
