steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/solanki-flask-app:$COMMIT_SHA', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/solanki-flask-app:$COMMIT_SHA']

  # Step 3: SSH into the Compute Engine and update the container
  -  name: 'gcr.io/cloud-builders/gcloud'
     args:
      - 'compute'
      - 'instances'
      - 'set-container-configuration'
      - '--zone=us-east1-a'
      - '--instance=solanki-flask-instance'
      - '--container-image=gcr.io/$PROJECT_ID/solanki-flask-app:$COMMIT_SHA'
options:

logs_bucket: 'gs://log_bucket-solanki'  # Specify the Cloud Storage bucket for logs
